/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giftcard.gui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class TarjetaGui extends javax.swing.JFrame {

    ArrayList<Tarjeta> listaT;
    String fila1[] = new String[]{"Código", "RUN", "Clave", "Monto", "Vigencia", "Trabajador"};
    DefaultTableModel tabla;
    int fila, columna;

    /**
     * Creates new form TarjetaGui
     */
    public TarjetaGui() {
        initComponents();
        listaT = new ArrayList<>();
        tabla = new DefaultTableModel(fila1, 0);
        tablaT.setModel(tabla);
        panelCompra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtRun = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtVigencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        crearTarjeta = new javax.swing.JButton();
        eliminarTarjeta = new javax.swing.JButton();
        modificarTarjeta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaT = new javax.swing.JTable();
        panelCompra = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        hacerCompra = new javax.swing.JButton();
        txtFinal = new javax.swing.JLabel();
        salir2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(2147483600, 2147483647));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/tarjeta.png"))); // NOI18N
        jLabel1.setText("Giftcards");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelForm.setBackground(new java.awt.Color(102, 153, 255));
        panelForm.setForeground(new java.awt.Color(0, 0, 102));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Nombre del trabajador");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtRun.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRunActionPerformed(evt);
            }
        });

        txtMonto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtVigencia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtVigencia.setForeground(new java.awt.Color(153, 153, 153));
        txtVigencia.setText("dd-MM-aaaa");
        txtVigencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVigenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVigenciaFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        salir.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setText("RUN sin DV:");

        crearTarjeta.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        crearTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/addGift.png"))); // NOI18N
        crearTarjeta.setText("Crear");
        crearTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTarjetaActionPerformed(evt);
            }
        });

        eliminarTarjeta.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        eliminarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/deleteGift.png"))); // NOI18N
        eliminarTarjeta.setText("Eliminar");
        eliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTarjetaActionPerformed(evt);
            }
        });

        modificarTarjeta.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        modificarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/modGift.png"))); // NOI18N
        modificarTarjeta.setText("Modificar");
        modificarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTarjetaActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/info.png"))); // NOI18N
        jLabel6.setText("Para modificar/eliminar, se debe tener seleccionada la fila que desea cambiar o eliminar.");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setText("Monto:");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel8.setText("Vigencia:");

        comprar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/carrito.png"))); // NOI18N
        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)))
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addComponent(crearTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(modificarTarjeta)))
                        .addGap(23, 23, 23)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(eliminarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(comprar))
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarTarjeta)
                    .addComponent(modificarTarjeta)
                    .addComponent(crearTarjeta)
                    .addComponent(comprar))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10))
        );

        panelTabla.setBackground(new java.awt.Color(102, 153, 255));
        panelTabla.setForeground(new java.awt.Color(0, 0, 102));

        tablaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaTAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaT);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCompra.setBackground(new java.awt.Color(102, 153, 255));
        panelCompra.setForeground(new java.awt.Color(102, 153, 255));

        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("RUN sin DV");
        txtUsuario.setToolTipText("");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel9.setText("Monto:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setText("Usuario:");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel7.setText("Contraseña:");

        txtSaldo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtSaldo.setText("Saldo restante: ");

        hacerCompra.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        hacerCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giftcard/gui/carrito.png"))); // NOI18N
        hacerCompra.setText("Hacer Compra");
        hacerCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerCompraActionPerformed(evt);
            }
        });

        txtFinal.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtFinal.setForeground(new java.awt.Color(0, 0, 0));

        salir2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        salir2.setText("Salir");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompraLayout = new javax.swing.GroupLayout(panelCompra);
        panelCompra.setLayout(panelCompraLayout);
        panelCompraLayout.setHorizontalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCompraLayout.createSequentialGroup()
                                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompraLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtClave)
                            .addComponent(txtTotal)))
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addComponent(txtSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addComponent(salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(hacerCompra)))
                .addContainerGap())
        );
        panelCompraLayout.setVerticalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo)
                    .addComponent(txtFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir2)
                    .addComponent(hacerCompra))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRunActionPerformed


    private void crearTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTarjetaActionPerformed
        // TODO add your handling code here:
        Validaciones v = new Validaciones();
        long codigo = generarCodigo();
        String run1 = txtRun.getText();

        String monto1 = txtMonto.getText();

        if (run1.equals("")) {
            run1 = "0";

        }
        if (monto1.equals("")) {
            monto1 = "0";

        }
        int run = Integer.parseInt(run1);
        int clave = run / 10000;
        String nombre = txtNombre.getText();
        int monto = Integer.parseInt(monto1);

        String fecha = txtVigencia.getText();
        boolean a = v.validarNombre(nombre);
        boolean b = v.validarFecha(fecha);
        boolean c = v.validarRun(run);
        boolean d = v.validarMonto2(monto);

        if (a == true && b == true && c == true && d == true) {

            listaT.add(new Tarjeta(codigo, run, clave, monto, fecha, nombre));
            tabla.setRowCount(0);
            for (int contador = 0; contador < listaT.size(); contador++) {
                Object[] datos = {listaT.get(contador).codigo, listaT.get(contador).run, listaT.get(contador).clave,
                    listaT.get(contador).monto, listaT.get(contador).vigencia, listaT.get(contador).nombre};
                tabla.addRow(datos);
            }
            borrar();
        }


    }//GEN-LAST:event_crearTarjetaActionPerformed
    public static long generarCodigo() {
        Random random = new Random();
        long codigo = (long) (1000000000000000L + random.nextFloat() * 9000000000000000L);
        return (codigo);
    }

    private void borrar() {

        txtNombre.setText("Nombre del trabajador");
        txtNombre.setForeground(new Color(153, 153, 153));
        txtRun.setText("");
        txtMonto.setText("");
        txtVigencia.setForeground(new Color(153, 153, 153));
        txtVigencia.setText("dd-MM-aaaa");

    }

    private void eliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTarjetaActionPerformed
        try {
            tabla.removeRow(fila);
            listaT.remove(fila);
            tabla.setRowCount(0);

            for (int contador = 0; contador < listaT.size(); contador++) {
                Object[] datos = {listaT.get(contador).codigo, listaT.get(contador).run, listaT.get(contador).clave,
                    listaT.get(contador).monto, listaT.get(contador).vigencia, listaT.get(contador).nombre};
                tabla.addRow(datos);
            }
            borrar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Recuerde seleccionar fila.");
        }

    }//GEN-LAST:event_eliminarTarjetaActionPerformed

    private void modificarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTarjetaActionPerformed
        try {
            Validaciones v = new Validaciones();

            String monto2 = txtMonto.getText();

            if (monto2.equals("")) {
                monto2 = "0";
            }

            String cambiarNombre = txtNombre.getText();
            int cambiarMonto = Integer.parseInt(monto2);
            String cambiarVigencia = txtVigencia.getText();

            String run1 = txtRun.getText();

            if (run1.equals("")) {
                run1 = "0";

            }

            int cambiarRun = Integer.parseInt(run1);
            int cambiarClave = (cambiarRun / 10000);

            boolean a = v.validarNombre(cambiarNombre);
            boolean b = v.validarFecha(cambiarVigencia);
            boolean c = v.validarRun(cambiarRun);
            boolean d = v.validarMonto2(cambiarMonto);

            if (a == true && b == true && c == true && d == true) {

                listaT.get(fila).nombre = cambiarNombre;
                listaT.get(fila).run = cambiarRun;
                listaT.get(fila).clave = cambiarClave;
                listaT.get(fila).monto = cambiarMonto;
                listaT.get(fila).vigencia = cambiarVigencia;
                tabla.setRowCount(0);

                for (int contador = 0; contador < listaT.size(); contador++) {
                    Object[] datos = {listaT.get(contador).codigo, listaT.get(contador).run, listaT.get(contador).clave,
                        listaT.get(contador).monto, listaT.get(contador).vigencia, listaT.get(contador).nombre};
                    tabla.addRow(datos);
                }
                borrar();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea modificar.");

        }


    }//GEN-LAST:event_modificarTarjetaActionPerformed

    private void tablaTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaTAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTAncestorAdded

    private void tablaTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTMouseClicked
        // TODO add your handling code here:
        fila = tablaT.getSelectedRow();
        columna = tablaT.getColumnCount();

        txtRun.setText(tabla.getValueAt(fila, 1).toString());
        txtMonto.setText(tabla.getValueAt(fila, 3).toString());
        txtVigencia.setText(tabla.getValueAt(fila, 4).toString());
        txtNombre.setText(tabla.getValueAt(fila, 5).toString());
        txtVigencia.setForeground(new Color(0, 0, 0));
        txtNombre.setForeground(new Color(0, 0, 0));

    }//GEN-LAST:event_tablaTMouseClicked

    private void txtVigenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVigenciaFocusGained
        if (txtVigencia.getText().equals("dd-MM-aaaa")) {
            txtVigencia.setText("");
            txtVigencia.setForeground(new Color(0, 0, 0));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtVigenciaFocusGained

    private void txtVigenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVigenciaFocusLost
        if (txtVigencia.getText().equals("")) {
            txtVigencia.setText("dd-MM-aaaa");
            txtVigencia.setForeground(new Color(153, 153, 153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVigenciaFocusLost

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if (txtNombre.getText().equals("Nombre del trabajador")) {
            txtNombre.setText("");
            txtNombre.setForeground(new Color(0, 0, 0));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if (txtNombre.getText().equals("")) {
            txtNombre.setText("Nombre del trabajador");
            txtNombre.setForeground(new Color(153, 153, 153));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusLost

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        setSize(415, 350);
        setLocationRelativeTo(null);
        panelCompra.setVisible(true);
        panelTabla.setVisible(false);
        panelForm.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_comprarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().equals("")) {
            txtUsuario.setText("RUN sin DV");
            txtUsuario.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("RUN sin DV")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(new Color(0, 0, 0));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void hacerCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerCompraActionPerformed

        Validaciones v = new Validaciones();

        String usuarioT = txtUsuario.getText();
        String totalT = txtTotal.getText();
        String claveT = txtClave.getText();
        boolean f = v.validarTres(usuarioT, claveT, totalT);
        if (f == true) {

            if (usuarioT.equals("RUN sin DV") || usuarioT.equals("")) {
                usuarioT = "0";
            }
            if (totalT.equals("")) {
                totalT = "0";
            }

            if (claveT.equals("")) {
                claveT = "0";
            }

            int usuario = Integer.parseInt(usuarioT);
            int clave1 = (Integer.parseInt(usuarioT)) / 10000;
            int clave = Integer.parseInt(claveT);

            int total = Integer.parseInt(totalT);

            boolean u = v.validarNombre(usuarioT);
            boolean m1 = v.validarMonto2(total);

            boolean t = v.validarUsuario(clave, clave1);

            if (t == true && m1 == true && u == true) {

                for (int contador = 0; contador < listaT.size(); contador++) {

                    if (listaT.get(contador).run == usuario) {
                        int b = listaT.get(contador).monto - total;
                        boolean m = v.validarMonto(b);
                        if  (m == true){
                            tabla.removeRow(contador);

                                b = listaT.get(contador).monto - total;
                                listaT.get(contador).monto = b;

                                Object[] datos = {listaT.get(contador).codigo, listaT.get(contador).run, listaT.get(contador).clave,
                                    listaT.get(contador).monto, listaT.get(contador).vigencia, listaT.get(contador).nombre};
                                tabla.addRow(datos);

                                txtFinal.setText(Integer.toString(listaT.get(contador).monto));
                            }
                        }

                    }

                }

            }

    }//GEN-LAST:event_hacerCompraActionPerformed

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed

        String run1 = txtRun.getText();

        String monto1 = txtMonto.getText();

        if (run1.equals("")) {
            run1 = "0";

        }
        if (monto1.equals("")) {
            monto1 = "0";

        }
        int run = 0;
        int clave = 0;
        String nombre = null;
        int monto = 0;

        String fecha = null;
        long codigo = 0;

        listaT.add(new Tarjeta(codigo, run, clave, monto, fecha, nombre));
        tabla.setRowCount(0);
        for (int contador = 0; contador < listaT.size(); contador++) {
            Object[] datos = {listaT.get(contador).codigo, listaT.get(contador).run, listaT.get(contador).clave,
                listaT.get(contador).monto, listaT.get(contador).vigencia, listaT.get(contador).nombre};
            tabla.addRow(datos);

        }

        borrar();

        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_salir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced intxtMonto SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarjetaGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarjetaGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarjetaGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarjetaGui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarjetaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprar;
    private javax.swing.JButton crearTarjeta;
    private javax.swing.JButton eliminarTarjeta;
    private javax.swing.JButton hacerCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarTarjeta;
    public javax.swing.JPanel panelCompra;
    public javax.swing.JPanel panelForm;
    public javax.swing.JPanel panelTabla;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir2;
    private javax.swing.JTable tablaT;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JLabel txtFinal;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRun;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVigencia;
    // End of variables declaration//GEN-END:variables
}
